import type { Config } from "tailwindcss";

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "var(--sc-color-background)",
        surface: "var(--sc-color-surface)",
        "surface-secondary": "var(--sc-color-surface-secondary)",
        navigation: "var(--sc-color-navigation)",
        selected: "var(--sc-color-selected)",
        hover: "var(--sc-color-hover)",
        border: "var(--sc-color-border)",
        "border-strong": "var(--sc-color-border-strong)",
        divider: "var(--sc-color-divider)",
        foreground: "var(--sc-color-text-primary)",
        "foreground-secondary": "var(--sc-color-text-secondary)",
        "foreground-muted": "var(--sc-color-text-muted)",
        action: "var(--sc-color-primary-action)",
        "action-hover": "var(--sc-color-primary-action-hover)",
        "action-pressed": "var(--sc-color-primary-action-pressed)",
        "action-foreground": "var(--sc-color-primary-action-text)",
        accent: "var(--sc-color-accent)",
        "accent-hover": "var(--sc-color-accent-hover)",
        "accent-pale": "var(--sc-color-accent-pale)",
        focus: "var(--sc-color-focus)",
        info: "var(--sc-color-info)",
        "info-surface": "var(--sc-color-info-surface)",
        success: "var(--sc-color-success)",
        "success-surface": "var(--sc-color-success-surface)",
        warning: "var(--sc-color-warning)",
        "warning-surface": "var(--sc-color-warning-surface)",
        blocking: "var(--sc-color-blocking)",
        "blocking-surface": "var(--sc-color-blocking-surface)",
        critical: "var(--sc-color-critical)",
        "critical-surface": "var(--sc-color-critical-surface)",
        "disabled-surface": "var(--sc-color-disabled-surface)",
        "disabled-border": "var(--sc-color-disabled-border)",
        "disabled-foreground": "var(--sc-color-disabled-text)",
      },
      borderRadius: {
        sc: "var(--sc-radius-md)",
        "sc-sm": "var(--sc-radius-sm)",
        "sc-lg": "var(--sc-radius-lg)",
      },
      boxShadow: {
        "sc-low": "var(--sc-shadow-low)",
        "sc-raised": "var(--sc-shadow-raised)",
      },
      maxWidth: {
        workspace: "var(--sc-content-width)",
      },
      transitionDuration: {
        fast: "var(--sc-motion-fast)",
        standard: "var(--sc-motion-standard)",
      },
    },
  },
  plugins: [],
} satisfies Config;
