-- Product table defaults (internal product master)
ALTER TABLE "Product" ADD COLUMN "flooring_brand" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_series" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_material" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_wear_layer" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_thickness_mm" DECIMAL;
ALTER TABLE "Product" ADD COLUMN "flooring_plank_length_in" DECIMAL;
ALTER TABLE "Product" ADD COLUMN "flooring_plank_width_in" DECIMAL;
ALTER TABLE "Product" ADD COLUMN "flooring_finish" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_edge" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_installation" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_underlayment" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_underlayment_mm" DECIMAL;
ALTER TABLE "Product" ADD COLUMN "flooring_water_resistance" TEXT;
ALTER TABLE "Product" ADD COLUMN "flooring_warranty_residential_yr" INTEGER;
ALTER TABLE "Product" ADD COLUMN "flooring_warranty_commercial_yr" INTEGER;
ALTER TABLE "Product" ADD COLUMN "flooring_box_coverage_sqft" DECIMAL;
ALTER TABLE "Product" ADD COLUMN "flooring_low_stock_threshold" DECIMAL;

-- Sales product table defaults (customer/order-facing source)
ALTER TABLE "products" ADD COLUMN "flooring_brand" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_series" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_material" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_wear_layer" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_thickness_mm" DECIMAL;
ALTER TABLE "products" ADD COLUMN "flooring_plank_length_in" DECIMAL;
ALTER TABLE "products" ADD COLUMN "flooring_plank_width_in" DECIMAL;
ALTER TABLE "products" ADD COLUMN "flooring_finish" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_edge" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_installation" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_underlayment" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_underlayment_mm" DECIMAL;
ALTER TABLE "products" ADD COLUMN "flooring_water_resistance" TEXT;
ALTER TABLE "products" ADD COLUMN "flooring_warranty_residential_yr" INTEGER;
ALTER TABLE "products" ADD COLUMN "flooring_warranty_commercial_yr" INTEGER;
ALTER TABLE "products" ADD COLUMN "flooring_box_coverage_sqft" DECIMAL;
ALTER TABLE "products" ADD COLUMN "flooring_low_stock_threshold" DECIMAL;
